export const caracteristicas=[
{"id_producto_caracteristica":"1","id_producto":"2","titulo":"","descripcion":"ALARMA FD 600"},
{"id_producto_caracteristica":"2","id_producto":"3","titulo":"","descripcion":"ALARMA GM 100"},
{"id_producto_caracteristica":"3","id_producto":"4","titulo":"","descripcion":"ALARMA VK 700"},
{"id_producto_caracteristica":"4","id_producto":"5","titulo":"","descripcion":"ALARMA"},
{"id_producto_caracteristica":"5","id_producto":"6","titulo":"","descripcion":"ALARMA"},
{"id_producto_caracteristica":"6","id_producto":"7","titulo":"","descripcion":"ALARMA"},
{"id_producto_caracteristica":"7","id_producto":"8","titulo":"","descripcion":"ALARMA"},
{"id_producto_caracteristica":"8","id_producto":"9","titulo":"","descripcion":"ALARMA"},
{"id_producto_caracteristica":"9","id_producto":"10","titulo":"","descripcion":"ALARMA"},
{"id_producto_caracteristica":"10","id_producto":"11","titulo":"","descripcion":"ALARMA"},
{"id_producto_caracteristica":"11","id_producto":"12","titulo":"","descripcion":"ACTUADOR"},
{"id_producto_caracteristica":"12","id_producto":"13","titulo":"","descripcion":"INMOVILIZADOR"},
{"id_producto_caracteristica":"13","id_producto":"14","titulo":"","descripcion":"MODULO ALZAVIDRIOS"},
{"id_producto_caracteristica":"14","id_producto":"15","titulo":"","descripcion":"RELEVADOR"},
{"id_producto_caracteristica":"15","id_producto":"16","titulo":"","descripcion":"FUSIBLE 12V"},
{"id_producto_caracteristica":"16","id_producto":"17","titulo":"","descripcion":"SENSOR BUZZER"},
{"id_producto_caracteristica":"17","id_producto":"18","titulo":"","descripcion":"SENSOR DISPLAY"},
{"id_producto_caracteristica":"18","id_producto":"19","titulo":"","descripcion":"SENSOR OEM"},
{"id_producto_caracteristica":"19","id_producto":"20","titulo":"","descripcion":"SENSOR 3 EN 1"},
{"id_producto_caracteristica":"20","id_producto":"21","titulo":"","descripcion":"CANCELADOR"},
{"id_producto_caracteristica":"21","id_producto":"22","titulo":"","descripcion":"RESISTENCIA"},
{"id_producto_caracteristica":"22","id_producto":"23","titulo":"","descripcion":"BAJA CARBON"},
{"id_producto_caracteristica":"23","id_producto":"24","titulo":"","descripcion":"BIXENON CARBON"},
{"id_producto_caracteristica":"24","id_producto":"25","titulo":"","descripcion":"HALOGENO CARBON"},
{"id_producto_caracteristica":"25","id_producto":"26","titulo":"","descripcion":"BAJA HID"},
{"id_producto_caracteristica":"26","id_producto":"27","titulo":"","descripcion":"BIXENON HID"},
{"id_producto_caracteristica":"27","id_producto":"28","titulo":"","descripcion":"HALOGENO HID"},
{"id_producto_caracteristica":"28","id_producto":"29","titulo":"","descripcion":"BAJA NONEX\/SIXTY"},
{"id_producto_caracteristica":"29","id_producto":"30","titulo":"","descripcion":"BIXENON NONEX\/SIXTY"},
{"id_producto_caracteristica":"30","id_producto":"31","titulo":"","descripcion":"HALOGENO NONEX\/SIXTY"},
{"id_producto_caracteristica":"31","id_producto":"32","titulo":"","descripcion":"Medidas: H1 H3 H4-1 H4-1L H4L H4HL H7 H10 H11 H13-1 H13L H13HL 880 9005 9006 9007L 9007L 9007HL 5202 D2C"},
{"id_producto_caracteristica":"32","id_producto":"33","titulo":"","descripcion":"BIXENON 55 W ECO"},
{"id_producto_caracteristica":"33","id_producto":"34","titulo":"","descripcion":"Medidas: H1 H3 H4-1 H4-1L H4L H4HL H7 H10 H11 H13-1 H13L H13HL 880 9005 9006 9007L 9007L 9007HL 5202 D2C"},
{"id_producto_caracteristica":"34","id_producto":"35","titulo":"","descripcion":"Medidas: H1 H3 H4-1 H4-1L H4L H4HL H7 H10 H11 H13-1 H13L H13HL 880 9005 9006 9007L 9007L 9007HL 5202 D2C"},
{"id_producto_caracteristica":"35","id_producto":"36","titulo":"","descripcion":"Medidas: H1 H3 H4-1 H4-1L H4L H4HL H7 H10 H11 H13-1 H13L H13HL 880 9005 9006 9007L 9007L 9007HL 5202 D2C"},
{"id_producto_caracteristica":"36","id_producto":"37","titulo":"","descripcion":"Medidas: H1 H3 H4-1 H4-1L H4L H4HL H7 H10 H11 H13-1 H13L H13HL 880 9005 9006 9007L 9007L 9007HL 5202 D2C"},
{"id_producto_caracteristica":"37","id_producto":"38","titulo":"","descripcion":"Medidas: H1 H3 H4-1 H4-1L H4L H4HL H7 H10 H11 H13-1 H13L H13HL 880 9005 9006 9007L 9007L 9007HL 5202 D2C"},
{"id_producto_caracteristica":"38","id_producto":"39","titulo":"","descripcion":"Medidas: H1 H3 H4-1 H4-1L H4L H4HL H7 H10 H11 H13-1 H13L H13HL 880 9005 9006 9007L 9007L 9007HL 5202 D2C"},
{"id_producto_caracteristica":"39","id_producto":"40","titulo":"","descripcion":"7.6\"  PULGADAS"},
{"id_producto_caracteristica":"40","id_producto":"41","titulo":"","descripcion":"13.7\"  PULGADAS"},
{"id_producto_caracteristica":"41","id_producto":"42","titulo":"","descripcion":"21.8\"  PULGADAS"},
{"id_producto_caracteristica":"42","id_producto":"43","titulo":"","descripcion":"31.8\"  PULGADAS"},
{"id_producto_caracteristica":"43","id_producto":"44","titulo":"","descripcion":"41.8\"  PULGADAS"},
{"id_producto_caracteristica":"44","id_producto":"45","titulo":"","descripcion":"SUPER ECO 520"},
{"id_producto_caracteristica":"45","id_producto":"46","titulo":"","descripcion":"52\"  PULGADAS"},
{"id_producto_caracteristica":"46","id_producto":"47","titulo":"","descripcion":"21.4\"  PULGADAS"},
{"id_producto_caracteristica":"47","id_producto":"48","titulo":"","descripcion":"41.2\"  PULGADAS"},
{"id_producto_caracteristica":"48","id_producto":"49","titulo":"","descripcion":"51.1\"  PULGADAS"},
{"id_producto_caracteristica":"49","id_producto":"50","titulo":"","descripcion":"7.5\"  PULGADAS"},
{"id_producto_caracteristica":"50","id_producto":"51","titulo":"","descripcion":"13.5\"  PULGADAS"},
{"id_producto_caracteristica":"51","id_producto":"52","titulo":"","descripcion":"21.5\"  PULGADAS"},
{"id_producto_caracteristica":"52","id_producto":"53","titulo":"","descripcion":"31.5\"  PULGADAS"},
{"id_producto_caracteristica":"53","id_producto":"54","titulo":"","descripcion":"5.5\"  PULGADAS"},
{"id_producto_caracteristica":"54","id_producto":"55","titulo":"","descripcion":"10.2\"  PULGADAS"},
{"id_producto_caracteristica":"55","id_producto":"56","titulo":"","descripcion":"15.0\"  PULGADAS"},
{"id_producto_caracteristica":"56","id_producto":"57","titulo":"","descripcion":"19.7\"  PULGADAS"},
{"id_producto_caracteristica":"57","id_producto":"58","titulo":"","descripcion":"24.4\"  PULGADAS"},
{"id_producto_caracteristica":"58","id_producto":"59","titulo":"","descripcion":"29.1\"  PULGADAS"},
{"id_producto_caracteristica":"59","id_producto":"60","titulo":"","descripcion":"38.6\"  PULGADAS"},
{"id_producto_caracteristica":"60","id_producto":"61","titulo":"","descripcion":"50\"  PULGADAS"},
{"id_producto_caracteristica":"61","id_producto":"62","titulo":"","descripcion":"9.4\"  PULGADAS"},
{"id_producto_caracteristica":"62","id_producto":"63","titulo":"","descripcion":"12.1\"  PULGADAS"},
{"id_producto_caracteristica":"63","id_producto":"64","titulo":"","descripcion":"14.9\"  PULGADAS"},
{"id_producto_caracteristica":"64","id_producto":"65","titulo":"","descripcion":"17.6\"  PULGADAS"},
{"id_producto_caracteristica":"65","id_producto":"66","titulo":"","descripcion":"20.3\"  PULGADAS"},
{"id_producto_caracteristica":"66","id_producto":"67","titulo":"","descripcion":"23.1\"  PULGADAS"},
{"id_producto_caracteristica":"67","id_producto":"68","titulo":"","descripcion":"44.9\" PULGADAS"},
{"id_producto_caracteristica":"68","id_producto":"69","titulo":"","descripcion":"7.5\"  PULGADAS"},
{"id_producto_caracteristica":"69","id_producto":"70","titulo":"","descripcion":"13.5\"  PULGADAS"},
{"id_producto_caracteristica":"70","id_producto":"71","titulo":"","descripcion":"21.4\"  PULGADAS"},
{"id_producto_caracteristica":"71","id_producto":"72","titulo":"","descripcion":"41.2\"  PULGADAS"},
{"id_producto_caracteristica":"72","id_producto":"73","titulo":"","descripcion":"51.1\"  PULGADAS"},
{"id_producto_caracteristica":"73","id_producto":"74","titulo":"","descripcion":"21.2\"  PULGADAS"},
{"id_producto_caracteristica":"74","id_producto":"75","titulo":"","descripcion":"41.0\"  PULGADAS"},
{"id_producto_caracteristica":"75","id_producto":"76","titulo":"","descripcion":"51\"  PULGADAS"},
{"id_producto_caracteristica":"76","id_producto":"77","titulo":"","descripcion":"21.2\"  PULGADAS"},
{"id_producto_caracteristica":"77","id_producto":"78","titulo":"","descripcion":"41.0\"  PULGADAS"},
{"id_producto_caracteristica":"78","id_producto":"79","titulo":"","descripcion":"51\"  PULGADAS"},
{"id_producto_caracteristica":"79","id_producto":"80","titulo":"","descripcion":"50\"  PULGADAS"},
{"id_producto_caracteristica":"80","id_producto":"81","titulo":"","descripcion":"TR 100 LENS 7\""},
{"id_producto_caracteristica":"81","id_producto":"82","titulo":"","descripcion":"REX 400 4D"},
{"id_producto_caracteristica":"82","id_producto":"83","titulo":"","descripcion":"REX 400"},
{"id_producto_caracteristica":"83","id_producto":"84","titulo":"","descripcion":"BALL 300"},
{"id_producto_caracteristica":"84","id_producto":"85","titulo":"","descripcion":"SQUARE 300"},
{"id_producto_caracteristica":"85","id_producto":"86","titulo":"","descripcion":"SQUARE 27W"},
{"id_producto_caracteristica":"86","id_producto":"87","titulo":"","descripcion":"45W"},
{"id_producto_caracteristica":"87","id_producto":"88","titulo":"","descripcion":"SQUARE 200"},
{"id_producto_caracteristica":"88","id_producto":"89","titulo":"","descripcion":"SQUARE 400"},
{"id_producto_caracteristica":"89","id_producto":"90","titulo":"","descripcion":"BALL 700"},
{"id_producto_caracteristica":"90","id_producto":"91","titulo":"","descripcion":"TR 800"},
{"id_producto_caracteristica":"91","id_producto":"92","titulo":"","descripcion":"REX 500"},
{"id_producto_caracteristica":"92","id_producto":"93","titulo":"","descripcion":"TR 700"},
{"id_producto_caracteristica":"93","id_producto":"94","titulo":"","descripcion":"BUMPER 600"},
{"id_producto_caracteristica":"94","id_producto":"95","titulo":"","descripcion":"REX 600"},
{"id_producto_caracteristica":"95","id_producto":"96","titulo":"","descripcion":"CIRCLE 27W"},
{"id_producto_caracteristica":"96","id_producto":"97","titulo":"","descripcion":"SQUARE 500"},
{"id_producto_caracteristica":"97","id_producto":"98","titulo":"","descripcion":"LED MADE IN USA"},
{"id_producto_caracteristica":"98","id_producto":"99","titulo":"","descripcion":"SLIM BAR 4000 42\" LED CREE"},
{"id_producto_caracteristica":"99","id_producto":"100","titulo":"","descripcion":"CABLE BOCINA CAL 10"},
{"id_producto_caracteristica":"100","id_producto":"101","titulo":"","descripcion":"FLASH BAR 5000 50\" LED CREE"},
{"id_producto_caracteristica":"101","id_producto":"102","titulo":"","descripcion":"POLICE  BAR 5000 50\" LED CREE"},
{"id_producto_caracteristica":"102","id_producto":"103","titulo":"","descripcion":"CABLE BOCINA CAL 12"},
{"id_producto_caracteristica":"103","id_producto":"104","titulo":"","descripcion":"CABLE BOCINA CAL 14"},
{"id_producto_caracteristica":"104","id_producto":"105","titulo":"","descripcion":"CABLE BOCINA CAL 16"},
{"id_producto_caracteristica":"105","id_producto":"106","titulo":"","descripcion":"CABLE BOCINA CAL 16 RMT"},
{"id_producto_caracteristica":"106","id_producto":"107","titulo":"","descripcion":"CABLE BOCINA CAL 18"},
{"id_producto_caracteristica":"107","id_producto":"108","titulo":"","descripcion":"CABLE BOCINA CAL 18 RMT"},
{"id_producto_caracteristica":"108","id_producto":"109","titulo":"","descripcion":"CABLE DE PODER CAL 0"},
{"id_producto_caracteristica":"109","id_producto":"110","titulo":"","descripcion":"CABLE DE PODER CAL 4"},
{"id_producto_caracteristica":"110","id_producto":"111","titulo":"","descripcion":"CABLE DE PODER CAL 8"},
{"id_producto_caracteristica":"111","id_producto":"112","titulo":"","descripcion":"1.5 metros"},
{"id_producto_caracteristica":"112","id_producto":"113","titulo":"","descripcion":"CONECTOR 1M 2F"},
{"id_producto_caracteristica":"113","id_producto":"114","titulo":"","descripcion":"CONECTOR 2M 1F"},
{"id_producto_caracteristica":"114","id_producto":"115","titulo":"","descripcion":"CABLE RCA 1M"},
{"id_producto_caracteristica":"115","id_producto":"116","titulo":"","descripcion":"CABLE RCA 3M"},
{"id_producto_caracteristica":"116","id_producto":"117","titulo":"","descripcion":"CABLE RCA 5M"},
{"id_producto_caracteristica":"117","id_producto":"118","titulo":"","descripcion":"CABLE RCA 9.25M"},
{"id_producto_caracteristica":"118","id_producto":"119","titulo":"","descripcion":"80A"},
{"id_producto_caracteristica":"119","id_producto":"120","titulo":"","descripcion":"CONECTOR 16-14 AWG"},
{"id_producto_caracteristica":"120","id_producto":"121","titulo":"","descripcion":"CHUPON 16-14"},
{"id_producto_caracteristica":"121","id_producto":"122","titulo":"","descripcion":"ZAPATA VINYL 16-14 AWN"},
{"id_producto_caracteristica":"122","id_producto":"123","titulo":"","descripcion":"CONECTOR 12-10 AWN"},
{"id_producto_caracteristica":"123","id_producto":"124","titulo":"","descripcion":"OJILLO 12-10 AWN"},
{"id_producto_caracteristica":"124","id_producto":"125","titulo":"","descripcion":"OJILLO 16-14 AWN"},
{"id_producto_caracteristica":"125","id_producto":"126","titulo":"","descripcion":"ZAPATA SEMIFORRADA 16-14 AWN"},
{"id_producto_caracteristica":"126","id_producto":"127","titulo":"","descripcion":"ZAPATA NYLON 16-14 AWN"},
{"id_producto_caracteristica":"127","id_producto":"128","titulo":"","descripcion":"ESPADA 16-14 AWN"},
{"id_producto_caracteristica":"128","id_producto":"129","titulo":"","descripcion":"KIT INSTALACIÓN CAL 0"},
{"id_producto_caracteristica":"129","id_producto":"130","titulo":"","descripcion":"KIT INSTALACIÓN CAL 10"},
{"id_producto_caracteristica":"130","id_producto":"131","titulo":"","descripcion":"KIT INSTALACIÓN CAL 4"},
{"id_producto_caracteristica":"131","id_producto":"132","titulo":"","descripcion":"KIT INSTALACIÓN CAL 6"},
{"id_producto_caracteristica":"132","id_producto":"133","titulo":"","descripcion":"KIT INSTALACIÓN CAL 8"},
{"id_producto_caracteristica":"133","id_producto":"134","titulo":"","descripcion":"CIRCLE CAM"},
{"id_producto_caracteristica":"134","id_producto":"135","titulo":"","descripcion":"CROMO CAM"},
{"id_producto_caracteristica":"135","id_producto":"136","titulo":"","descripcion":"INFRA CAM"},
{"id_producto_caracteristica":"136","id_producto":"137","titulo":"","descripcion":"LED CAM"},
{"id_producto_caracteristica":"137","id_producto":"138","titulo":"","descripcion":"METAL CAM"},
{"id_producto_caracteristica":"138","id_producto":"139","titulo":"","descripcion":"PIN CAM"},
{"id_producto_caracteristica":"139","id_producto":"140","titulo":"","descripcion":"PIN LED CAM"},
{"id_producto_caracteristica":"140","id_producto":"141","titulo":"","descripcion":"MULTI CAM"},
{"id_producto_caracteristica":"141","id_producto":"142","titulo":"","descripcion":"PLACA CAM"},
{"id_producto_caracteristica":"142","id_producto":"143","titulo":"","descripcion":"PLACA CROMO CAM"},
{"id_producto_caracteristica":"143","id_producto":"144","titulo":"","descripcion":"CERAMICA"},
{"id_producto_caracteristica":"144","id_producto":"145","titulo":"","descripcion":"PLÁSTICO"},
{"id_producto_caracteristica":"145","id_producto":"146","titulo":"","descripcion":"POP FLASH"},
{"id_producto_caracteristica":"146","id_producto":"147","titulo":"","descripcion":"PIN COB"},
{"id_producto_caracteristica":"147","id_producto":"148","titulo":"","descripcion":"MINI COB"},
{"id_producto_caracteristica":"148","id_producto":"149","titulo":"","descripcion":"SKY COB 48"},
{"id_producto_caracteristica":"149","id_producto":"150","titulo":"","descripcion":"SKY COB 36"},
{"id_producto_caracteristica":"150","id_producto":"151","titulo":"","descripcion":"SKY COB 24"},
{"id_producto_caracteristica":"151","id_producto":"152","titulo":"","descripcion":"SKY COB 18"},
{"id_producto_caracteristica":"152","id_producto":"153","titulo":"","descripcion":"FESTOON 41"},
{"id_producto_caracteristica":"153","id_producto":"154","titulo":"","descripcion":"FESTOON 39"},
{"id_producto_caracteristica":"154","id_producto":"155","titulo":"","descripcion":"FESTOON 36"},
{"id_producto_caracteristica":"155","id_producto":"156","titulo":"","descripcion":"FESTOON 31"},
{"id_producto_caracteristica":"156","id_producto":"157","titulo":"","descripcion":"CERAMICA"},
{"id_producto_caracteristica":"157","id_producto":"158","titulo":"","descripcion":"ROCK COB 2"},
{"id_producto_caracteristica":"158","id_producto":"159","titulo":"","descripcion":"ROCK COB 1P"},
{"id_producto_caracteristica":"159","id_producto":"160","titulo":"","descripcion":"ROCK COB 2P"},
{"id_producto_caracteristica":"160","id_producto":"161","titulo":"","descripcion":"ROCK 3 LUPA"},
{"id_producto_caracteristica":"161","id_producto":"162","titulo":"","descripcion":"POP 8"},
{"id_producto_caracteristica":"162","id_producto":"163","titulo":"","descripcion":"POP LUPA"},
{"id_producto_caracteristica":"163","id_producto":"164","titulo":"","descripcion":"LED MOTO"},
{"id_producto_caracteristica":"164","id_producto":"165","titulo":"","descripcion":"GRAPAS 3528"},
{"id_producto_caracteristica":"165","id_producto":"166","titulo":"","descripcion":"GRAPAS 5050"},
{"id_producto_caracteristica":"166","id_producto":"167","titulo":"","descripcion":"CONECTOR FLASH"},
{"id_producto_caracteristica":"167","id_producto":"168","titulo":"","descripcion":"CONTROL RGB"},
{"id_producto_caracteristica":"168","id_producto":"169","titulo":"","descripcion":"MODULO 5 LED"},
{"id_producto_caracteristica":"169","id_producto":"170","titulo":"","descripcion":"MODULO 5 LED RGB"},
{"id_producto_caracteristica":"170","id_producto":"171","titulo":"","descripcion":"TIRA DE LED 3528"},
{"id_producto_caracteristica":"171","id_producto":"172","titulo":"","descripcion":"TIRA DE LED 5050"},
{"id_producto_caracteristica":"172","id_producto":"173","titulo":"","descripcion":"TIRA DE LED 3528 RGB"},
{"id_producto_caracteristica":"173","id_producto":"174","titulo":"","descripcion":"TIRA DE LED 5050 RGB"},
{"id_producto_caracteristica":"174","id_producto":"175","titulo":"","descripcion":"OJO DE ÁNGEL"},
{"id_producto_caracteristica":"175","id_producto":"176","titulo":"","descripcion":"LUPA OJO DE ANGEL 89MM"},
{"id_producto_caracteristica":"176","id_producto":"177","titulo":"","descripcion":"U3"},
{"id_producto_caracteristica":"177","id_producto":"178","titulo":"","descripcion":"ESTROBOS"},
{"id_producto_caracteristica":"178","id_producto":"179","titulo":"","descripcion":"30 cm Blanca"},
{"id_producto_caracteristica":"179","id_producto":"180","titulo":"","descripcion":"45cm blanca"},
{"id_producto_caracteristica":"180","id_producto":"181","titulo":"","descripcion":"60cm   Blanca"},
{"id_producto_caracteristica":"181","id_producto":"182","titulo":"","descripcion":"TUBO FLEXIBLE 30cm  B\/A"},
{"id_producto_caracteristica":"182","id_producto":"183","titulo":"","descripcion":"TUBO FLEXIBLE 45cm  Blanca\/Ambar"},
{"id_producto_caracteristica":"183","id_producto":"184","titulo":"","descripcion":"TUBO FLEXIBLE 60cm  Blanca\/Ambar"},
{"id_producto_caracteristica":"184","id_producto":"185","titulo":"","descripcion":"ROCK GEL 2"},
{"id_producto_caracteristica":"185","id_producto":"186","titulo":"","descripcion":"ROCK GEL 3"},
{"id_producto_caracteristica":"186","id_producto":"187","titulo":"","descripcion":"POP GEL CAN BUS"},
{"id_producto_caracteristica":"187","id_producto":"188","titulo":"","descripcion":"FESTOON 31 CAN BUS"},
{"id_producto_caracteristica":"188","id_producto":"189","titulo":"","descripcion":"FESTOON 36 CAN BUS"},
{"id_producto_caracteristica":"189","id_producto":"190","titulo":"","descripcion":"FESTOON 39 CAN BUS"},
{"id_producto_caracteristica":"190","id_producto":"191","titulo":"","descripcion":"FESTOON 41 CAN BUS"},
{"id_producto_caracteristica":"191","id_producto":"192","titulo":"","descripcion":"VP 100"},
{"id_producto_caracteristica":"192","id_producto":"193","titulo":"","descripcion":"VP 200"},
{"id_producto_caracteristica":"193","id_producto":"194","titulo":"","descripcion":"VP 300"},
{"id_producto_caracteristica":"194","id_producto":"195","titulo":"","descripcion":"80A"},
{"id_producto_caracteristica":"195","id_producto":"196","titulo":"","descripcion":"41.5\"  PULGADAS"},
{"id_producto_caracteristica":"196","id_producto":"197","titulo":"","descripcion":"50\"  PULGADAS"},
{"id_producto_caracteristica":"197","id_producto":"198","titulo":"","descripcion":"ECO BAR 80"},
{"id_producto_caracteristica":"198","id_producto":"199","titulo":"","descripcion":"ECO BAR 140"},
{"id_producto_caracteristica":"199","id_producto":"200","titulo":"","descripcion":"ECO BAR 220"},
{"id_producto_caracteristica":"200","id_producto":"201","titulo":"","descripcion":"ECO BAR 320"},
{"id_producto_caracteristica":"201","id_producto":"202","titulo":"","descripcion":"ECO BAR 420"},
{"id_producto_caracteristica":"202","id_producto":"203","titulo":"","descripcion":"ECO BAR 520"},
{"id_producto_caracteristica":"203","id_producto":"29","titulo":"","descripcion":"Medidas: H1 H3 H4-1 H4-1L H4L H4HL H7 H10 H11 H13-1 H13L H13HL 880 9005 9006 9007L 9007L 9007HL 5202 D2C"},
{"id_producto_caracteristica":"204","id_producto":"30","titulo":"","descripcion":"Medidas: H1 H3 H4-1 H4-1L H4L H4HL H7 H10 H11 H13-1 H13L H13HL 880 9005 9006 9007L 9007L 9007HL 5202 D2C"},
{"id_producto_caracteristica":"205","id_producto":"31","titulo":"","descripcion":"Medidas: H1 H3 H4-1 H4-1L H4L H4HL H7 H10 H11 H13-1 H13L H13HL 880 9005 9006 9007L 9007L 9007HL 5202 D2C"},
{"id_producto_caracteristica":"206","id_producto":"204","titulo":"","descripcion":"D.C"},
{"id_producto_caracteristica":"207","id_producto":"20","titulo":"","descripcion":"Camara de reversa display"},
{"id_producto_caracteristica":"208","id_producto":"20","titulo":"","descripcion":"negro"},
{"id_producto_caracteristica":"209","id_producto":"205","titulo":"","descripcion":"Car USB"},
{"id_producto_caracteristica":"210","id_producto":"205","titulo":"","descripcion":"SD"},
{"id_producto_caracteristica":"211","id_producto":"205","titulo":"","descripcion":"Mp3"},
{"id_producto_caracteristica":"212","id_producto":"205","titulo":"","descripcion":"PLAYBACK With Radio Receiver"},
{"id_producto_caracteristica":"213","id_producto":"205","titulo":"","descripcion":"Bluetooh"},
{"id_producto_caracteristica":"214","id_producto":"205","titulo":"","descripcion":"PLL"},
{"id_producto_caracteristica":"215","id_producto":"205","titulo":"","descripcion":"FM"},
{"id_producto_caracteristica":"216","id_producto":"54","titulo":"","descripcion":"13.97  CENTIMETROS"},
{"id_producto_caracteristica":"217","id_producto":"54","titulo":"","descripcion":"18  WATTS"},
{"id_producto_caracteristica":"218","id_producto":"54","titulo":"","descripcion":"6  LEDS"},
{"id_producto_caracteristica":"219","id_producto":"55","titulo":"","descripcion":"25.9  CENTIMETROS"},
{"id_producto_caracteristica":"220","id_producto":"55","titulo":"","descripcion":"36  WATTS"},
{"id_producto_caracteristica":"221","id_producto":"55","titulo":"","descripcion":"12  LEDS"},
{"id_producto_caracteristica":"222","id_producto":"56","titulo":"","descripcion":"38.1  CENTIMETROS"},
{"id_producto_caracteristica":"223","id_producto":"56","titulo":"","descripcion":"54  WATTS"},
{"id_producto_caracteristica":"224","id_producto":"56","titulo":"","descripcion":"18  LEDS"},
{"id_producto_caracteristica":"225","id_producto":"57","titulo":"","descripcion":"50.03  CENTIMETROS"},
{"id_producto_caracteristica":"226","id_producto":"57","titulo":"","descripcion":"72  WATTS"},
{"id_producto_caracteristica":"227","id_producto":"57","titulo":"","descripcion":"24  LEDS"},
{"id_producto_caracteristica":"228","id_producto":"58","titulo":"","descripcion":"61.9  CENTIMETROS"},
{"id_producto_caracteristica":"229","id_producto":"58","titulo":"","descripcion":"90   WATTS"},
{"id_producto_caracteristica":"230","id_producto":"58","titulo":"","descripcion":"30  LEDS"},
{"id_producto_caracteristica":"231","id_producto":"59","titulo":"","descripcion":"73.9  CENTIMETROS"},
{"id_producto_caracteristica":"232","id_producto":"59","titulo":"","descripcion":"108  WATTS"},
{"id_producto_caracteristica":"233","id_producto":"59","titulo":"","descripcion":"36  LEDS"},
{"id_producto_caracteristica":"234","id_producto":"60","titulo":"","descripcion":"98.04  CENTIMETROS"},
{"id_producto_caracteristica":"235","id_producto":"60","titulo":"","descripcion":"144  WATTS"},
{"id_producto_caracteristica":"236","id_producto":"60","titulo":"","descripcion":"48  LEDS"},
{"id_producto_caracteristica":"237","id_producto":"61","titulo":"","descripcion":"126  CENTIMETROS"},
{"id_producto_caracteristica":"238","id_producto":"61","titulo":"","descripcion":"160  WATTS"},
{"id_producto_caracteristica":"239","id_producto":"61","titulo":"","descripcion":"53  LEDS"},
{"id_producto_caracteristica":"240","id_producto":"50","titulo":"","descripcion":"19  CENTIMETROS"},
{"id_producto_caracteristica":"241","id_producto":"50","titulo":"","descripcion":"36  WATTS"},
{"id_producto_caracteristica":"242","id_producto":"50","titulo":"","descripcion":"12  LEDS"},
{"id_producto_caracteristica":"243","id_producto":"236","titulo":"","descripcion":"7.6\"  PULGADAS"},
{"id_producto_caracteristica":"244","id_producto":"236","titulo":"","descripcion":"19.3  CENTIMETROS"},
{"id_producto_caracteristica":"245","id_producto":"236","titulo":"","descripcion":"36  WATTS"},
{"id_producto_caracteristica":"246","id_producto":"236","titulo":"","descripcion":"12  LEDS"},
{"id_producto_caracteristica":"247","id_producto":"237","titulo":"","descripcion":"13.7\"  PULGADAS"},
{"id_producto_caracteristica":"248","id_producto":"237","titulo":"","descripcion":"34.7  CENTIMETROS"},
{"id_producto_caracteristica":"249","id_producto":"237","titulo":"","descripcion":"72  WATTS"},
{"id_producto_caracteristica":"250","id_producto":"237","titulo":"","descripcion":"24  LEDS"},
{"id_producto_caracteristica":"251","id_producto":"238","titulo":"","descripcion":"21.8\"  PULGADAS"},
{"id_producto_caracteristica":"252","id_producto":"238","titulo":"","descripcion":"55.3  CENTIMETROS"},
{"id_producto_caracteristica":"253","id_producto":"238","titulo":"","descripcion":"120  PULGADAS"},
{"id_producto_caracteristica":"254","id_producto":"238","titulo":"","descripcion":"40  LEDS"},
{"id_producto_caracteristica":"255","id_producto":"239","titulo":"","descripcion":"31.8\"  PULGADAS"},
{"id_producto_caracteristica":"256","id_producto":"239","titulo":"","descripcion":"80.7  CENTIMETROS"},
{"id_producto_caracteristica":"257","id_producto":"239","titulo":"","descripcion":"180  WATTS"},
{"id_producto_caracteristica":"258","id_producto":"239","titulo":"","descripcion":"60  LEDS"},
{"id_producto_caracteristica":"259","id_producto":"240","titulo":"","descripcion":"41.8\"  PULGADAS"},
{"id_producto_caracteristica":"260","id_producto":"240","titulo":"","descripcion":"106.1  CENTIMETROS"},
{"id_producto_caracteristica":"261","id_producto":"240","titulo":"","descripcion":"240  WATTS"},
{"id_producto_caracteristica":"262","id_producto":"240","titulo":"","descripcion":"80  LEDS"},
{"id_producto_caracteristica":"263","id_producto":"241","titulo":"","descripcion":"52\"  PULGADAS"},
{"id_producto_caracteristica":"264","id_producto":"241","titulo":"","descripcion":"132  CENTIMETROS"},
{"id_producto_caracteristica":"265","id_producto":"241","titulo":"","descripcion":"300  WATTS"},
{"id_producto_caracteristica":"266","id_producto":"241","titulo":"","descripcion":"100  LEDS"},
{"id_producto_caracteristica":"267","id_producto":"51","titulo":"","descripcion":"34.2  CENTIMETROS"},
{"id_producto_caracteristica":"268","id_producto":"51","titulo":"","descripcion":"72 WATTS"},
{"id_producto_caracteristica":"269","id_producto":"51","titulo":"","descripcion":"24  LEDS"},
{"id_producto_caracteristica":"270","id_producto":"52","titulo":"","descripcion":"54.61  CENTIMETROS"},
{"id_producto_caracteristica":"271","id_producto":"52","titulo":"","descripcion":"120  WATTS"},
{"id_producto_caracteristica":"272","id_producto":"52","titulo":"","descripcion":"40  LEDS"},
{"id_producto_caracteristica":"273","id_producto":"53","titulo":"","descripcion":"80  CENTIMETROS"},
{"id_producto_caracteristica":"274","id_producto":"53","titulo":"","descripcion":"180  WATTS"},
{"id_producto_caracteristica":"275","id_producto":"53","titulo":"","descripcion":"60 LEDS"},
{"id_producto_caracteristica":"276","id_producto":"196","titulo":"","descripcion":"105.41  CENTIMETROS"},
{"id_producto_caracteristica":"277","id_producto":"196","titulo":"","descripcion":"240  WATTS"},
{"id_producto_caracteristica":"278","id_producto":"196","titulo":"","descripcion":"80  LEDS"},
{"id_producto_caracteristica":"279","id_producto":"197","titulo":"","descripcion":"127  CENTIMETROS"},
{"id_producto_caracteristica":"280","id_producto":"197","titulo":"","descripcion":"300  WATTS"},
{"id_producto_caracteristica":"281","id_producto":"197","titulo":"","descripcion":"100  LEDS"},
{"id_producto_caracteristica":"282","id_producto":"242","titulo":"","descripcion":"6.7\"  PULGADAS"},
{"id_producto_caracteristica":"283","id_producto":"242","titulo":"","descripcion":"17  CENTIMETROS"},
{"id_producto_caracteristica":"284","id_producto":"242","titulo":"","descripcion":"36  WATTS"},
{"id_producto_caracteristica":"285","id_producto":"242","titulo":"","descripcion":"12  LEDS"},
{"id_producto_caracteristica":"286","id_producto":"62","titulo":"","descripcion":"34.2  CENTIMETROS"},
{"id_producto_caracteristica":"287","id_producto":"62","titulo":"","descripcion":"54  WATTS"},
{"id_producto_caracteristica":"288","id_producto":"62","titulo":"","descripcion":"18  LEDS"},
{"id_producto_caracteristica":"289","id_producto":"63","titulo":"","descripcion":"30.7  CENTIMETROS"},
{"id_producto_caracteristica":"290","id_producto":"63","titulo":"","descripcion":"72  WATTS"},
{"id_producto_caracteristica":"291","id_producto":"63","titulo":"","descripcion":"24  LEDS"},
{"id_producto_caracteristica":"292","id_producto":"64","titulo":"","descripcion":"37.84  CENTIMETROS"},
{"id_producto_caracteristica":"293","id_producto":"64","titulo":"","descripcion":"90  WATTS"},
{"id_producto_caracteristica":"294","id_producto":"64","titulo":"","descripcion":"30  LEDS"},
{"id_producto_caracteristica":"295","id_producto":"65","titulo":"","descripcion":"44.6  CENTIMETROS"},
{"id_producto_caracteristica":"296","id_producto":"65","titulo":"","descripcion":"108  WATTS"},
{"id_producto_caracteristica":"297","id_producto":"65","titulo":"","descripcion":"36  LEDS"},
{"id_producto_caracteristica":"298","id_producto":"66","titulo":"","descripcion":"51.56  CENTIMETROS"},
{"id_producto_caracteristica":"299","id_producto":"66","titulo":"","descripcion":"126  WATTS"},
{"id_producto_caracteristica":"300","id_producto":"66","titulo":"","descripcion":"42  LEDS"},
{"id_producto_caracteristica":"301","id_producto":"67","titulo":"","descripcion":"58.67  CENTIMETROS"},
{"id_producto_caracteristica":"302","id_producto":"67","titulo":"","descripcion":"144  WATTS"},
{"id_producto_caracteristica":"303","id_producto":"67","titulo":"","descripcion":"48  LEDS"},
{"id_producto_caracteristica":"304","id_producto":"68","titulo":"","descripcion":"114  CENTIMETROS"},
{"id_producto_caracteristica":"305","id_producto":"68","titulo":"","descripcion":"288  WATTS"},
{"id_producto_caracteristica":"306","id_producto":"68","titulo":"","descripcion":"96  LEDS"},
{"id_producto_caracteristica":"307","id_producto":"243","titulo":"","descripcion":"28.5\"  PULGADAS"},
{"id_producto_caracteristica":"308","id_producto":"243","titulo":"","descripcion":"72.39  CENTIMETROS"},
{"id_producto_caracteristica":"309","id_producto":"243","titulo":"","descripcion":"180  WATTS"},
{"id_producto_caracteristica":"310","id_producto":"243","titulo":"","descripcion":"60 LEDS"},
{"id_producto_caracteristica":"311","id_producto":"40","titulo":"","descripcion":"19.3  CENTIMETROS"},
{"id_producto_caracteristica":"312","id_producto":"40","titulo":"","descripcion":"36  WATTS"},
{"id_producto_caracteristica":"313","id_producto":"40","titulo":"","descripcion":"12  LEDS"},
{"id_producto_caracteristica":"314","id_producto":"41","titulo":"","descripcion":"34.7  CENTIMETROS"},
{"id_producto_caracteristica":"315","id_producto":"41","titulo":"","descripcion":"72  WATTS"},
{"id_producto_caracteristica":"316","id_producto":"41","titulo":"","descripcion":"24  LEDS"},
{"id_producto_caracteristica":"317","id_producto":"42","titulo":"","descripcion":"55.3  CENTIMETROS"},
{"id_producto_caracteristica":"318","id_producto":"42","titulo":"","descripcion":"120  WATTS"},
{"id_producto_caracteristica":"319","id_producto":"42","titulo":"","descripcion":"40  LEDS"},
{"id_producto_caracteristica":"320","id_producto":"43","titulo":"","descripcion":"80.7  CENTIMETROS"},
{"id_producto_caracteristica":"321","id_producto":"43","titulo":"","descripcion":"180  WATTS"},
{"id_producto_caracteristica":"322","id_producto":"43","titulo":"","descripcion":"60  LEDS"},
{"id_producto_caracteristica":"323","id_producto":"44","titulo":"","descripcion":"106.1  CENTIMETROS"},
{"id_producto_caracteristica":"324","id_producto":"44","titulo":"","descripcion":"240  WATTS"},
{"id_producto_caracteristica":"325","id_producto":"44","titulo":"","descripcion":"80  LEDS"},
{"id_producto_caracteristica":"326","id_producto":"46","titulo":"","descripcion":"123.08  CENTIMETROS"},
{"id_producto_caracteristica":"327","id_producto":"46","titulo":"","descripcion":"240  WATTS"},
{"id_producto_caracteristica":"328","id_producto":"46","titulo":"","descripcion":"80  LEDS"},
{"id_producto_caracteristica":"329","id_producto":"69","titulo":"","descripcion":"19  CENTIMETROS"},
{"id_producto_caracteristica":"330","id_producto":"69","titulo":"","descripcion":"36  WATTS"},
{"id_producto_caracteristica":"331","id_producto":"69","titulo":"","descripcion":"12  LEDS"},
{"id_producto_caracteristica":"332","id_producto":"70","titulo":"","descripcion":"34.2  CENTIMETROS"},
{"id_producto_caracteristica":"333","id_producto":"70","titulo":"","descripcion":"72  WATTS"},
{"id_producto_caracteristica":"334","id_producto":"70","titulo":"","descripcion":"24  LEDS"},
{"id_producto_caracteristica":"335","id_producto":"71","titulo":"","descripcion":"54.3  CENTIMETROS"},
{"id_producto_caracteristica":"336","id_producto":"71","titulo":"","descripcion":"120  WATTS"},
{"id_producto_caracteristica":"337","id_producto":"71","titulo":"","descripcion":"40  LEDS"},
{"id_producto_caracteristica":"338","id_producto":"244","titulo":"","descripcion":"31.3\"  PULGADAS"},
{"id_producto_caracteristica":"339","id_producto":"244","titulo":"","descripcion":"79.5  CENTIMETROS"},
{"id_producto_caracteristica":"340","id_producto":"244","titulo":"","descripcion":"180  WATTS"},
{"id_producto_caracteristica":"341","id_producto":"244","titulo":"","descripcion":"60  LEDS"},
{"id_producto_caracteristica":"342","id_producto":"72","titulo":"","descripcion":"104.6  CENTIMETROS"},
{"id_producto_caracteristica":"343","id_producto":"72","titulo":"","descripcion":"240  WATTS"},
{"id_producto_caracteristica":"344","id_producto":"72","titulo":"","descripcion":"80  LEDS"},
{"id_producto_caracteristica":"345","id_producto":"73","titulo":"","descripcion":"129.1  CENTIMETROS"},
{"id_producto_caracteristica":"346","id_producto":"73","titulo":"","descripcion":"300  WATTS"},
{"id_producto_caracteristica":"347","id_producto":"73","titulo":"","descripcion":"100  LEDS"},
{"id_producto_caracteristica":"348","id_producto":"245","titulo":"","descripcion":"5.6\"  PULGADAS"},
{"id_producto_caracteristica":"349","id_producto":"245","titulo":"","descripcion":"14  CENTIMETROS"},
{"id_producto_caracteristica":"350","id_producto":"245","titulo":"","descripcion":"24  WATTS"},
{"id_producto_caracteristica":"351","id_producto":"245","titulo":"","descripcion":"8  LEDS"},
{"id_producto_caracteristica":"352","id_producto":"246","titulo":"","descripcion":"7.5\"  PULGADAS"},
{"id_producto_caracteristica":"353","id_producto":"246","titulo":"","descripcion":"19  CENTIMETROS"},
{"id_producto_caracteristica":"354","id_producto":"246","titulo":"","descripcion":"36  WATTS"},
{"id_producto_caracteristica":"355","id_producto":"246","titulo":"","descripcion":"12  LEDS"},
{"id_producto_caracteristica":"356","id_producto":"247","titulo":"","descripcion":"13.5\"  PULGADAS"},
{"id_producto_caracteristica":"357","id_producto":"247","titulo":"","descripcion":"34.3  CENTIMETROS"},
{"id_producto_caracteristica":"358","id_producto":"247","titulo":"","descripcion":"72  WATTS"},
{"id_producto_caracteristica":"359","id_producto":"247","titulo":"","descripcion":"24  LEDS"},
{"id_producto_caracteristica":"360","id_producto":"47","titulo":"","descripcion":"54.3  CENTIMETROS"},
{"id_producto_caracteristica":"361","id_producto":"47","titulo":"","descripcion":"120   WATTS"},
{"id_producto_caracteristica":"362","id_producto":"47","titulo":"","descripcion":"40  LEDS"},
{"id_producto_caracteristica":"363","id_producto":"248","titulo":"","descripcion":"31.3\"  PULGADAS"},
{"id_producto_caracteristica":"364","id_producto":"248","titulo":"","descripcion":"79.5  CENTIMETROS"},
{"id_producto_caracteristica":"365","id_producto":"248","titulo":"","descripcion":"180  WATS"},
{"id_producto_caracteristica":"366","id_producto":"248","titulo":"","descripcion":"60  LEDS"},
{"id_producto_caracteristica":"367","id_producto":"48","titulo":"","descripcion":"104.6  CENTIMETROS"},
{"id_producto_caracteristica":"368","id_producto":"48","titulo":"","descripcion":"420  WATTS"},
{"id_producto_caracteristica":"369","id_producto":"48","titulo":"","descripcion":"140  LEDS"},
{"id_producto_caracteristica":"370","id_producto":"49","titulo":"","descripcion":"129.1  CENTIMETROS"},
{"id_producto_caracteristica":"371","id_producto":"49","titulo":"","descripcion":"300  WATTS"},
{"id_producto_caracteristica":"372","id_producto":"49","titulo":"","descripcion":"100  LEDS"},
{"id_producto_caracteristica":"373","id_producto":"249","titulo":"","descripcion":"7.3\"  PULGADAS"},
{"id_producto_caracteristica":"374","id_producto":"249","titulo":"","descripcion":"19  CENTIMETROS"},
{"id_producto_caracteristica":"375","id_producto":"249","titulo":"","descripcion":"30  WATTS"},
{"id_producto_caracteristica":"376","id_producto":"249","titulo":"","descripcion":"10  LEDS"},
{"id_producto_caracteristica":"377","id_producto":"250","titulo":"","descripcion":"11.2\"  PULGADAS"},
{"id_producto_caracteristica":"378","id_producto":"250","titulo":"","descripcion":"29  CENTIMETROS"},
{"id_producto_caracteristica":"379","id_producto":"250","titulo":"","descripcion":"50  WATTS"},
{"id_producto_caracteristica":"380","id_producto":"74","titulo":"","descripcion":"54.3  CENTIMETROS"},
{"id_producto_caracteristica":"381","id_producto":"74","titulo":"","descripcion":"100  WATTS"},
{"id_producto_caracteristica":"382","id_producto":"74","titulo":"","descripcion":"33 LEDS"},
{"id_producto_caracteristica":"383","id_producto":"250","titulo":"","descripcion":"16  LEDS"},
{"id_producto_caracteristica":"384","id_producto":"251","titulo":"","descripcion":"25.5\"  PULGADAS"},
{"id_producto_caracteristica":"385","id_producto":"251","titulo":"","descripcion":"64.7  CENTIMETROS"},
{"id_producto_caracteristica":"386","id_producto":"251","titulo":"","descripcion":"120  WATTS"},
{"id_producto_caracteristica":"387","id_producto":"251","titulo":"","descripcion":"40  LEDS"},
{"id_producto_caracteristica":"388","id_producto":"75","titulo":"","descripcion":"104  CENTIMETROS"},
{"id_producto_caracteristica":"389","id_producto":"75","titulo":"","descripcion":"200 WATTS"},
{"id_producto_caracteristica":"390","id_producto":"75","titulo":"","descripcion":"66 LEDS"},
{"id_producto_caracteristica":"391","id_producto":"252","titulo":"","descripcion":"31.1\"  PULGADAS"},
{"id_producto_caracteristica":"392","id_producto":"252","titulo":"","descripcion":"79.5  CENTIMETROS"},
{"id_producto_caracteristica":"393","id_producto":"252","titulo":"","descripcion":"150  WATTS"},
{"id_producto_caracteristica":"394","id_producto":"252","titulo":"","descripcion":"50  LEDS"},
{"id_producto_caracteristica":"395","id_producto":"76","titulo":"","descripcion":"129.1  CENTIMETROS"},
{"id_producto_caracteristica":"396","id_producto":"76","titulo":"","descripcion":"250  WATTS"},
{"id_producto_caracteristica":"397","id_producto":"76","titulo":"","descripcion":"83  LEDS"},
{"id_producto_caracteristica":"398","id_producto":"253","titulo":"","descripcion":"7.3\"  PULGADAS"},
{"id_producto_caracteristica":"399","id_producto":"253","titulo":"","descripcion":"19  CENTIMETROS"},
{"id_producto_caracteristica":"400","id_producto":"253","titulo":"","descripcion":"30  WATTS"},
{"id_producto_caracteristica":"401","id_producto":"253","titulo":"","descripcion":"10  LEDS"},
{"id_producto_caracteristica":"402","id_producto":"254","titulo":"","descripcion":"11.2\"  PULGADAS"},
{"id_producto_caracteristica":"403","id_producto":"254","titulo":"","descripcion":"29  CENTIMETROS"},
{"id_producto_caracteristica":"404","id_producto":"254","titulo":"","descripcion":"50 WATTS"},
{"id_producto_caracteristica":"405","id_producto":"254","titulo":"","descripcion":"16 LEDS"},
{"id_producto_caracteristica":"406","id_producto":"77","titulo":"","descripcion":"54.3  CENTIMETROS"},
{"id_producto_caracteristica":"407","id_producto":"77","titulo":"","descripcion":"100  WATTS"},
{"id_producto_caracteristica":"408","id_producto":"77","titulo":"","descripcion":"33  LEDS"},
{"id_producto_caracteristica":"409","id_producto":"255","titulo":"","descripcion":"31.1\"  PULGADAS"},
{"id_producto_caracteristica":"410","id_producto":"255","titulo":"","descripcion":"79.5  CENTIMETROS"},
{"id_producto_caracteristica":"411","id_producto":"255","titulo":"","descripcion":"150  WATTS"},
{"id_producto_caracteristica":"412","id_producto":"255","titulo":"","descripcion":"50  LEDS"},
{"id_producto_caracteristica":"413","id_producto":"78","titulo":"","descripcion":"104.6  CENTIMETROS"},
{"id_producto_caracteristica":"414","id_producto":"78","titulo":"","descripcion":"200  WATTS"},
{"id_producto_caracteristica":"415","id_producto":"78","titulo":"","descripcion":"66  LEDS"},
{"id_producto_caracteristica":"416","id_producto":"79","titulo":"","descripcion":"129.1  CENTIMETROS"},
{"id_producto_caracteristica":"417","id_producto":"79","titulo":"","descripcion":"250  WATTS"},
{"id_producto_caracteristica":"418","id_producto":"79","titulo":"","descripcion":"83  LEDS"},
{"id_producto_caracteristica":"419","id_producto":"257","titulo":"","descripcion":"CHOPPER  BALL"},
{"id_producto_caracteristica":"420","id_producto":"258","titulo":"","descripcion":"BALL 500"},
{"id_producto_caracteristica":"421","id_producto":"259","titulo":"","descripcion":"TR 700 PROYECTOR"},
{"id_producto_caracteristica":"422","id_producto":"260","titulo":"","descripcion":"CABLE ESTROBO"},
{"id_producto_caracteristica":"423","id_producto":"261","titulo":"","descripcion":"CABLE ESTROBO"},
{"id_producto_caracteristica":"424","id_producto":"16","titulo":"","descripcion":"BOTON LUMINOSO"},
{"id_producto_caracteristica":"425","id_producto":"16","titulo":"","descripcion":"RELAY 40A"},
{"id_producto_caracteristica":"426","id_producto":"16","titulo":"","descripcion":"5M CABLE CORRIENTE"},
{"id_producto_caracteristica":"427","id_producto":"16","titulo":"","descripcion":"5M CABLE REMOTO"},
{"id_producto_caracteristica":"428","id_producto":"16","titulo":"","descripcion":"5M CABLE TIERRA"},
{"id_producto_caracteristica":"429","id_producto":"262","titulo":"","descripcion":"CONECTOR RGB"},
{"id_producto_caracteristica":"430","id_producto":"119","titulo":"","descripcion":"100A"},
{"id_producto_caracteristica":"431","id_producto":"119","titulo":"","descripcion":"120A"},
{"id_producto_caracteristica":"432","id_producto":"119","titulo":"","descripcion":"150A"},
{"id_producto_caracteristica":"433","id_producto":"119","titulo":"","descripcion":"180A"},
{"id_producto_caracteristica":"434","id_producto":"195","titulo":"","descripcion":"100A"},
{"id_producto_caracteristica":"435","id_producto":"195","titulo":"","descripcion":"120A"},
{"id_producto_caracteristica":"436","id_producto":"195","titulo":"","descripcion":"150A"},
{"id_producto_caracteristica":"437","id_producto":"195","titulo":"","descripcion":"180A"},
{"id_producto_caracteristica":"438","id_producto":"263","titulo":"","descripcion":"41.8\"  PULGADAS"},
{"id_producto_caracteristica":"439","id_producto":"263","titulo":"","descripcion":"106.1  CENTIMETROS"},
{"id_producto_caracteristica":"440","id_producto":"263","titulo":"","descripcion":"240  WATTS"},
{"id_producto_caracteristica":"441","id_producto":"263","titulo":"","descripcion":"80  LEDS"},
{"id_producto_caracteristica":"442","id_producto":"80","titulo":"","descripcion":"127  CETIMETROS"},
{"id_producto_caracteristica":"443","id_producto":"80","titulo":"","descripcion":"300  WATTS"},
{"id_producto_caracteristica":"444","id_producto":"80","titulo":"","descripcion":"100 LEDS"},
{"id_producto_caracteristica":"445","id_producto":"264","titulo":"","descripcion":"50\"  PULGADAS"},
{"id_producto_caracteristica":"446","id_producto":"264","titulo":"","descripcion":"127  CENTIMETROS"},
{"id_producto_caracteristica":"447","id_producto":"264","titulo":"","descripcion":"300  WATTS"},
{"id_producto_caracteristica":"448","id_producto":"264","titulo":"","descripcion":"100  LEDS"},
{"id_producto_caracteristica":"449","id_producto":"265","titulo":"","descripcion":"ROCK GEL 1"},
{"id_producto_caracteristica":"450","id_producto":"266","titulo":"","descripcion":"POP GEL"},
{"id_producto_caracteristica":"451","id_producto":"270","titulo":"","descripcion":"8.7\" pulgadas"},
{"id_producto_caracteristica":"452","id_producto":"270","titulo":"","descripcion":"23 centimetros"},
{"id_producto_caracteristica":"453","id_producto":"270","titulo":"","descripcion":"10 watts"},
{"id_producto_caracteristica":"454","id_producto":"271","titulo":"","descripcion":"16.6\" pulgadas"},
{"id_producto_caracteristica":"455","id_producto":"271","titulo":"","descripcion":"42.5 centimetros"},
{"id_producto_caracteristica":"456","id_producto":"271","titulo":"","descripcion":"20 watts"},
{"id_producto_caracteristica":"457","id_producto":"272","titulo":"","descripcion":"24.5\" pulgadas"},
{"id_producto_caracteristica":"458","id_producto":"272","titulo":"","descripcion":"62 centimetros"},
{"id_producto_caracteristica":"459","id_producto":"272","titulo":"","descripcion":"30 watts"},
{"id_producto_caracteristica":"460","id_producto":"273","titulo":"","descripcion":"32.2\" pulgadas"},
{"id_producto_caracteristica":"461","id_producto":"273","titulo":"","descripcion":"82 centimetros"},
{"id_producto_caracteristica":"462","id_producto":"273","titulo":"","descripcion":"40 watts"},
{"id_producto_caracteristica":"463","id_producto":"274","titulo":"","descripcion":"42.2\" pulgadas"},
{"id_producto_caracteristica":"464","id_producto":"274","titulo":"","descripcion":"102 centimetros"},
{"id_producto_caracteristica":"465","id_producto":"274","titulo":"","descripcion":"50 watts"},
{"id_producto_caracteristica":"466","id_producto":"275","titulo":"","descripcion":"48\" pulgadas"},
{"id_producto_caracteristica":"467","id_producto":"275","titulo":"","descripcion":"122 centimetros"},
{"id_producto_caracteristica":"468","id_producto":"275","titulo":"","descripcion":"60 watts"},
{"id_producto_caracteristica":"469","id_producto":"699","titulo":"","descripcion":"SENSOR BUZZER"},
{"id_producto_caracteristica":"470","id_producto":"700","titulo":"","descripcion":"SENSOR BUZZER-CROMO"},
{"id_producto_caracteristica":"471","id_producto":"701","titulo":"","descripcion":"SENSOR BUZZER-PLATA"},
{"id_producto_caracteristica":"472","id_producto":"702","titulo":"","descripcion":"SENSOR DISPLAY-BLANCO"},
{"id_producto_caracteristica":"473","id_producto":"703","titulo":"","descripcion":"SENSOR DISPLAY-CROMO"},
{"id_producto_caracteristica":"474","id_producto":"704","titulo":"","descripcion":"SENSOR DISPLAY-PLATA"},
{"id_producto_caracteristica":"475","id_producto":"956","titulo":"","descripcion":"Rollo de cable de poder cal 4 GA PRO MAX"}
]