export const paises=[
    {"id_pais":"1","codigo":"AFG","descripcion":"Afganistán"},
    {"id_pais":"2","codigo":"ALA","descripcion":"Islas Åland"},
    {"id_pais":"3","codigo":"ALB","descripcion":"Albania"},
    {"id_pais":"4","codigo":"DEU","descripcion":"Alemania"},
    {"id_pais":"5","codigo":"AND","descripcion":"Andorra"},
    {"id_pais":"6","codigo":"AGO","descripcion":"Angola"},
    {"id_pais":"7","codigo":"AIA","descripcion":"Anguila"},
    {"id_pais":"8","codigo":"ATA","descripcion":"Antártida"},
    {"id_pais":"9","codigo":"ATG","descripcion":"Antigua y Barbuda"},
    {"id_pais":"10","codigo":"SAU","descripcion":"Arabia Saudita"},
    {"id_pais":"11","codigo":"DZA","descripcion":"Argelia"},
    {"id_pais":"12","codigo":"ARG","descripcion":"Argentina"},
    {"id_pais":"13","codigo":"ARM","descripcion":"Armenia"},
    {"id_pais":"14","codigo":"ABW","descripcion":"Aruba"},
    {"id_pais":"15","codigo":"AUS","descripcion":"Australia"},
    {"id_pais":"16","codigo":"AUT","descripcion":"Austria"},
    {"id_pais":"17","codigo":"AZE","descripcion":"Azerbaiyán"},
    {"id_pais":"18","codigo":"BHS","descripcion":"Bahamas (las)"},
    {"id_pais":"19","codigo":"BGD","descripcion":"Bangladés"},
    {"id_pais":"20","codigo":"BRB","descripcion":"Barbados"},
    {"id_pais":"21","codigo":"BHR","descripcion":"Baréin"},
    {"id_pais":"22","codigo":"BEL","descripcion":"Bélgica"},
    {"id_pais":"23","codigo":"BLZ","descripcion":"Belice"},
    {"id_pais":"24","codigo":"BEN","descripcion":"Benín"},
    {"id_pais":"25","codigo":"BMU","descripcion":"Bermudas"},
    {"id_pais":"26","codigo":"BLR","descripcion":"Bielorrusia"},
    {"id_pais":"27","codigo":"MMR","descripcion":"Myanmar"},
    {"id_pais":"28","codigo":"BOL","descripcion":"Bolivia, Estado Plurinacional de"},
    {"id_pais":"29","codigo":"BIH","descripcion":"Bosnia y Herzegovina"},
    {"id_pais":"30","codigo":"BWA","descripcion":"Botsuana"},
    {"id_pais":"31","codigo":"BRA","descripcion":"Brasil"},
    {"id_pais":"32","codigo":"BRN","descripcion":"Brunéi Darussalam"},
    {"id_pais":"33","codigo":"BGR","descripcion":"Bulgaria"},
    {"id_pais":"34","codigo":"BFA","descripcion":"Burkina Faso"},
    {"id_pais":"35","codigo":"BDI","descripcion":"Burundi"},
    {"id_pais":"36","codigo":"BTN","descripcion":"Bután"},
    {"id_pais":"37","codigo":"CPV","descripcion":"Cabo Verde"},
    {"id_pais":"38","codigo":"KHM","descripcion":"Camboya"},
    {"id_pais":"39","codigo":"CMR","descripcion":"Camerún"},
    {"id_pais":"40","codigo":"CAN","descripcion":"Canadá"},
    {"id_pais":"41","codigo":"QAT","descripcion":"Catar"},
    {"id_pais":"42","codigo":"BES","descripcion":"Bonaire, San Eustaquio y Saba"},
    {"id_pais":"43","codigo":"TCD","descripcion":"Chad"},
    {"id_pais":"44","codigo":"CHL","descripcion":"Chile"},
    {"id_pais":"45","codigo":"CHN","descripcion":"China"},
    {"id_pais":"46","codigo":"CYP","descripcion":"Chipre"},
    {"id_pais":"47","codigo":"COL","descripcion":"Colombia"},
    {"id_pais":"48","codigo":"COM","descripcion":"Comoras"},
    {"id_pais":"49","codigo":"PRK","descripcion":"Corea (la República Democrática Popular de)"},
    {"id_pais":"50","codigo":"KOR","descripcion":"Corea (la República de)"},
    {"id_pais":"51","codigo":"CIV","descripcion":"Côte d'Ivoire"},
    {"id_pais":"52","codigo":"CRI","descripcion":"Costa Rica"},
    {"id_pais":"53","codigo":"HRV","descripcion":"Croacia"},
    {"id_pais":"54","codigo":"CUB","descripcion":"Cuba"},
    {"id_pais":"55","codigo":"CUW","descripcion":"Curaçao"},
    {"id_pais":"56","codigo":"DNK","descripcion":"Dinamarca"},
    {"id_pais":"57","codigo":"DMA","descripcion":"Dominica"},
    {"id_pais":"58","codigo":"ECU","descripcion":"Ecuador"},
    {"id_pais":"59","codigo":"EGY","descripcion":"Egipto"},
    {"id_pais":"60","codigo":"SLV","descripcion":"El Salvador"},
    {"id_pais":"61","codigo":"ARE","descripcion":"Emiratos Árabes Unidos (Los)"},
    {"id_pais":"62","codigo":"ERI","descripcion":"Eritrea"},
    {"id_pais":"63","codigo":"SVK","descripcion":"Eslovaquia"},
    {"id_pais":"64","codigo":"SVN","descripcion":"Eslovenia"},
    {"id_pais":"65","codigo":"ESP","descripcion":"España"},
    {"id_pais":"66","codigo":"USA","descripcion":"Estados Unidos (los)"},
    {"id_pais":"67","codigo":"EST","descripcion":"Estonia"},
    {"id_pais":"68","codigo":"ETH","descripcion":"Etiopía"},
    {"id_pais":"69","codigo":"PHL","descripcion":"Filipinas (las)"},
    {"id_pais":"70","codigo":"FIN","descripcion":"Finlandia"},
    {"id_pais":"71","codigo":"FJI","descripcion":"Fiyi"},
    {"id_pais":"72","codigo":"FRA","descripcion":"Francia"},
    {"id_pais":"73","codigo":"GAB","descripcion":"Gabón"},
    {"id_pais":"74","codigo":"GMB","descripcion":"Gambia (La)"},
    {"id_pais":"75","codigo":"GEO","descripcion":"Georgia"},
    {"id_pais":"76","codigo":"GHA","descripcion":"Ghana"},
    {"id_pais":"77","codigo":"GIB","descripcion":"Gibraltar"},
    {"id_pais":"78","codigo":"GRD","descripcion":"Granada"},
    {"id_pais":"79","codigo":"GRC","descripcion":"Grecia"},
    {"id_pais":"80","codigo":"GRL","descripcion":"Groenlandia"},
    {"id_pais":"81","codigo":"GLP","descripcion":"Guadalupe"},
    {"id_pais":"82","codigo":"GUM","descripcion":"Guam"},
    {"id_pais":"83","codigo":"GTM","descripcion":"Guatemala"},
    {"id_pais":"84","codigo":"GUF","descripcion":"Guayana Francesa"},
    {"id_pais":"85","codigo":"GGY","descripcion":"Guernsey"},
    {"id_pais":"86","codigo":"GIN","descripcion":"Guinea"},
    {"id_pais":"87","codigo":"GNB","descripcion":"Guinea-Bisáu"},
    {"id_pais":"88","codigo":"GNQ","descripcion":"Guinea Ecuatorial"},
    {"id_pais":"89","codigo":"GUY","descripcion":"Guyana"},
    {"id_pais":"90","codigo":"HTI","descripcion":"Haití"},
    {"id_pais":"91","codigo":"HND","descripcion":"Honduras"},
    {"id_pais":"92","codigo":"HKG","descripcion":"Hong Kong"},
    {"id_pais":"93","codigo":"HUN","descripcion":"Hungría"},
    {"id_pais":"94","codigo":"IND","descripcion":"India"},
    {"id_pais":"95","codigo":"IDN","descripcion":"Indonesia"},
    {"id_pais":"96","codigo":"IRQ","descripcion":"Irak"},
    {"id_pais":"97","codigo":"IRN","descripcion":"Irán (la República Islámica de)"},
    {"id_pais":"98","codigo":"IRL","descripcion":"Irlanda"},
    {"id_pais":"99","codigo":"BVT","descripcion":"Isla Bouvet"},
    {"id_pais":"100","codigo":"IMN","descripcion":"Isla de Man"},
    {"id_pais":"101","codigo":"CXR","descripcion":"Isla de Navidad"},
    {"id_pais":"102","codigo":"NFK","descripcion":"Isla Norfolk"},
    {"id_pais":"103","codigo":"ISL","descripcion":"Islandia"},
    {"id_pais":"104","codigo":"CYM","descripcion":"Islas Caimán (las)"},
    {"id_pais":"105","codigo":"CCK","descripcion":"Islas Cocos (Keeling)"},
    {"id_pais":"106","codigo":"COK","descripcion":"Islas Cook (las)"},
    {"id_pais":"107","codigo":"FRO","descripcion":"Islas Feroe (las)"},
    {"id_pais":"108","codigo":"SGS","descripcion":"Georgia del sur y las islas sandwich del sur"},
    {"id_pais":"109","codigo":"HMD","descripcion":"Isla Heard e Islas McDonald"},
    {"id_pais":"110","codigo":"FLK","descripcion":"Islas Malvinas [Falkland] (las)"},
    {"id_pais":"111","codigo":"MNP","descripcion":"Islas Marianas del Norte (las)"},
    {"id_pais":"112","codigo":"MHL","descripcion":"Islas Marshall (las)"},
    {"id_pais":"113","codigo":"PCN","descripcion":"Pitcairn"},
    {"id_pais":"114","codigo":"SLB","descripcion":"Islas Salomón (las)"},
    {"id_pais":"115","codigo":"TCA","descripcion":"Islas Turcas y Caicos (las)"},
    {"id_pais":"116","codigo":"UMI","descripcion":"Islas de Ultramar Menores de Estados Unidos (las)"},
    {"id_pais":"117","codigo":"VGB","descripcion":"Islas Vírgenes (Británicas)"},
    {"id_pais":"118","codigo":"VIR","descripcion":"Islas Vírgenes (EE.UU.)"},
    {"id_pais":"119","codigo":"ISR","descripcion":"Israel"},
    {"id_pais":"120","codigo":"ITA","descripcion":"Italia"},
    {"id_pais":"121","codigo":"JAM","descripcion":"Jamaica"},
    {"id_pais":"122","codigo":"JPN","descripcion":"Japón"},
    {"id_pais":"123","codigo":"JEY","descripcion":"Jersey"},
    {"id_pais":"124","codigo":"JOR","descripcion":"Jordania"},
    {"id_pais":"125","codigo":"KAZ","descripcion":"Kazajistán"},
    {"id_pais":"126","codigo":"KEN","descripcion":"Kenia"},
    {"id_pais":"127","codigo":"KGZ","descripcion":"Kirguistán"},
    {"id_pais":"128","codigo":"KIR","descripcion":"Kiribati"},
    {"id_pais":"129","codigo":"KWT","descripcion":"Kuwait"},
    {"id_pais":"130","codigo":"LAO","descripcion":"Lao, (la) República Democrática Popular"},
    {"id_pais":"131","codigo":"LSO","descripcion":"Lesoto"},
    {"id_pais":"132","codigo":"LVA","descripcion":"Letonia"},
    {"id_pais":"133","codigo":"LBN","descripcion":"Líbano"},
    {"id_pais":"134","codigo":"LBR","descripcion":"Liberia"},
    {"id_pais":"135","codigo":"LBY","descripcion":"Libia"},
    {"id_pais":"136","codigo":"LIE","descripcion":"Liechtenstein"},
    {"id_pais":"137","codigo":"LTU","descripcion":"Lituania"},
    {"id_pais":"138","codigo":"LUX","descripcion":"Luxemburgo"},
    {"id_pais":"139","codigo":"MAC","descripcion":"Macao"},
    {"id_pais":"140","codigo":"MDG","descripcion":"Madagascar"},
    {"id_pais":"141","codigo":"MYS","descripcion":"Malasia"},
    {"id_pais":"142","codigo":"MWI","descripcion":"Malaui"},
    {"id_pais":"143","codigo":"MDV","descripcion":"Maldivas"},
    {"id_pais":"144","codigo":"MLI","descripcion":"Malí"},
    {"id_pais":"145","codigo":"MLT","descripcion":"Malta"},
    {"id_pais":"146","codigo":"MAR","descripcion":"Marruecos"},
    {"id_pais":"147","codigo":"MTQ","descripcion":"Martinica"},
    {"id_pais":"148","codigo":"MUS","descripcion":"Mauricio"},
    {"id_pais":"149","codigo":"MRT","descripcion":"Mauritania"},
    {"id_pais":"150","codigo":"MYT","descripcion":"Mayotte"},
    {"id_pais":"151","codigo":"MEX","descripcion":"México"},
    {"id_pais":"152","codigo":"FSM","descripcion":"Micronesia (los Estados Federados de)"},
    {"id_pais":"153","codigo":"MDA","descripcion":"Moldavia (la República de)"},
    {"id_pais":"154","codigo":"MCO","descripcion":"Mónaco"},
    {"id_pais":"155","codigo":"MNG","descripcion":"Mongolia"},
    {"id_pais":"156","codigo":"MNE","descripcion":"Montenegro"},
    {"id_pais":"157","codigo":"MSR","descripcion":"Montserrat"},
    {"id_pais":"158","codigo":"MOZ","descripcion":"Mozambique"},
    {"id_pais":"159","codigo":"NAM","descripcion":"Namibia"},
    {"id_pais":"160","codigo":"NRU","descripcion":"Nauru"},
    {"id_pais":"161","codigo":"NPL","descripcion":"Nepal"},
    {"id_pais":"162","codigo":"NIC","descripcion":"Nicaragua"},
    {"id_pais":"163","codigo":"NER","descripcion":"Níger (el)"},
    {"id_pais":"164","codigo":"NGA","descripcion":"Nigeria"},
    {"id_pais":"165","codigo":"NIU","descripcion":"Niue"},
    {"id_pais":"166","codigo":"NOR","descripcion":"Noruega"},
    {"id_pais":"167","codigo":"NCL","descripcion":"Nueva Caledonia"},
    {"id_pais":"168","codigo":"NZL","descripcion":"Nueva Zelanda"},
    {"id_pais":"169","codigo":"OMN","descripcion":"Omán"},
    {"id_pais":"170","codigo":"NLD","descripcion":"Países Bajos (los)"},
    {"id_pais":"171","codigo":"PAK","descripcion":"Pakistán"},
    {"id_pais":"172","codigo":"PLW","descripcion":"Palaos"},
    {"id_pais":"173","codigo":"PSE","descripcion":"Palestina, Estado de"},
    {"id_pais":"174","codigo":"PAN","descripcion":"Panamá"},
    {"id_pais":"175","codigo":"PNG","descripcion":"Papúa Nueva Guinea"},
    {"id_pais":"176","codigo":"PRY","descripcion":"Paraguay"},
    {"id_pais":"177","codigo":"PER","descripcion":"Perú"},
    {"id_pais":"178","codigo":"PYF","descripcion":"Polinesia Francesa"},
    {"id_pais":"179","codigo":"POL","descripcion":"Polonia"},
    {"id_pais":"180","codigo":"PRT","descripcion":"Portugal"},
    {"id_pais":"181","codigo":"PRI","descripcion":"Puerto Rico"},
    {"id_pais":"182","codigo":"GBR","descripcion":"Reino Unido (el)"},
    {"id_pais":"183","codigo":"CAF","descripcion":"República Centroafricana (la)"},
    {"id_pais":"184","codigo":"CZE","descripcion":"República Checa (la)"},
    {"id_pais":"185","codigo":"MKD","descripcion":"Macedonia (la antigua República Yugoslava de)"},
    {"id_pais":"186","codigo":"COG","descripcion":"Congo"},
    {"id_pais":"187","codigo":"COD","descripcion":"Congo (la República Democrática del)"},
    {"id_pais":"188","codigo":"DOM","descripcion":"República Dominicana (la)"},
    {"id_pais":"189","codigo":"REU","descripcion":"Reunión"},
    {"id_pais":"190","codigo":"RWA","descripcion":"Ruanda"},
    {"id_pais":"191","codigo":"ROU","descripcion":"Rumania"},
    {"id_pais":"192","codigo":"RUS","descripcion":"Rusia, (la) Federación de"},
    {"id_pais":"193","codigo":"ESH","descripcion":"Sahara Occidental"},
    {"id_pais":"194","codigo":"WSM","descripcion":"Samoa"},
    {"id_pais":"195","codigo":"ASM","descripcion":"Samoa Americana"},
    {"id_pais":"196","codigo":"BLM","descripcion":"San Bartolomé"},
    {"id_pais":"197","codigo":"KNA","descripcion":"San Cristóbal y Nieves"},
    {"id_pais":"198","codigo":"SMR","descripcion":"San Marino"},
    {"id_pais":"199","codigo":"MAF","descripcion":"San Martín (parte francesa)"},
    {"id_pais":"200","codigo":"SPM","descripcion":"San Pedro y Miquelón"},
    {"id_pais":"201","codigo":"VCT","descripcion":"San Vicente y las Granadinas"},
    {"id_pais":"202","codigo":"SHN","descripcion":"Santa Helena, Ascensión y Tristán de Acuña"},
    {"id_pais":"203","codigo":"LCA","descripcion":"Santa Lucía"},
    {"id_pais":"204","codigo":"STP","descripcion":"Santo Tomé y Príncipe"},
    {"id_pais":"205","codigo":"SEN","descripcion":"Senegal"},
    {"id_pais":"206","codigo":"SRB","descripcion":"Serbia"},
    {"id_pais":"207","codigo":"SYC","descripcion":"Seychelles"},
    {"id_pais":"208","codigo":"SLE","descripcion":"Sierra leona"},
    {"id_pais":"209","codigo":"SGP","descripcion":"Singapur"},
    {"id_pais":"210","codigo":"SXM","descripcion":"Sint Maarten (parte holandesa)"},
    {"id_pais":"211","codigo":"SYR","descripcion":"Siria, (la) República Árabe"},
    {"id_pais":"212","codigo":"SOM","descripcion":"Somalia"},
    {"id_pais":"213","codigo":"LKA","descripcion":"Sri Lanka"},
    {"id_pais":"214","codigo":"SWZ","descripcion":"Suazilandia"},
    {"id_pais":"215","codigo":"ZAF","descripcion":"Sudáfrica"},
    {"id_pais":"216","codigo":"SDN","descripcion":"Sudán (el)"},
    {"id_pais":"217","codigo":"SSD","descripcion":"Sudán del Sur"},
    {"id_pais":"218","codigo":"SWE","descripcion":"Suecia"},
    {"id_pais":"219","codigo":"CHE","descripcion":"Suiza"},
    {"id_pais":"220","codigo":"SUR","descripcion":"Surinam"},
    {"id_pais":"221","codigo":"SJM","descripcion":"Svalbard y Jan Mayen"},
    {"id_pais":"222","codigo":"THA","descripcion":"Tailandia"},
    {"id_pais":"223","codigo":"TWN","descripcion":"Taiwán (Provincia de China)"},
    {"id_pais":"224","codigo":"TZA","descripcion":"Tanzania, República Unida de"},
    {"id_pais":"225","codigo":"TJK","descripcion":"Tayikistán"},
    {"id_pais":"226","codigo":"IOT","descripcion":"Territorio Británico del Océano Índico (el)"},
    {"id_pais":"227","codigo":"ATF","descripcion":"Territorios Australes Franceses (los)"},
    {"id_pais":"228","codigo":"TLS","descripcion":"Timor-Leste"},
    {"id_pais":"229","codigo":"TGO","descripcion":"Togo"},
    {"id_pais":"230","codigo":"TKL","descripcion":"Tokelau"},
    {"id_pais":"231","codigo":"TON","descripcion":"Tonga"},
    {"id_pais":"232","codigo":"TTO","descripcion":"Trinidad y Tobago"},
    {"id_pais":"233","codigo":"TUN","descripcion":"Túnez"},
    {"id_pais":"234","codigo":"TKM","descripcion":"Turkmenistán"},
    {"id_pais":"235","codigo":"TUR","descripcion":"Turquía"},
    {"id_pais":"236","codigo":"TUV","descripcion":"Tuvalu"},
    {"id_pais":"237","codigo":"UKR","descripcion":"Ucrania"},
    {"id_pais":"238","codigo":"UGA","descripcion":"Uganda"},
    {"id_pais":"239","codigo":"URY","descripcion":"Uruguay"},
    {"id_pais":"240","codigo":"UZB","descripcion":"Uzbekistán"},
    {"id_pais":"241","codigo":"VUT","descripcion":"Vanuatu"},
    {"id_pais":"242","codigo":"VAT","descripcion":"Santa Sede[Estado de la Ciudad del Vaticano] (la)"},
    {"id_pais":"243","codigo":"VEN","descripcion":"Venezuela, República Bolivariana de"},
    {"id_pais":"244","codigo":"VNM","descripcion":"Viet Nam"},
    {"id_pais":"245","codigo":"WLF","descripcion":"Wallis y Futuna"},
    {"id_pais":"246","codigo":"YEM","descripcion":"Yemen"},
    {"id_pais":"247","codigo":"DJI","descripcion":"Yibuti"},
    {"id_pais":"248","codigo":"ZMB","descripcion":"Zambia"},
    {"id_pais":"249","codigo":"ZWE","descripcion":"Zimbabue"},
    {"id_pais":"250","codigo":"ZZZ","descripcion":"Países no declarados"}
    ]